maliit/keyboard

- src/keyboard/keyboard.cpp
Otherwise it would end up using the xdg-shell or whatever default is
from compositor and that may end up with wrongly positioned and treated
by compositor.
Other compositors using the maliit I know uses maliit-server instead so
this does not affect them as far as I understand.
> keyboard: use correct shell integration for maliit-keyboard

- src/plugin/inputmethod.cpp
- src/plugin/inputmethod_p.h
This includes 2 commits:
- Set mask regardless of qt platform, we should always set this regardless of what platform we are on
- Set disabled height on wayland if settings is set, this allows height to be set to 0 if the settings for disabled height is set on wayland also
> Wayland fixes

- src/plugin/inputmethod.cpp
Don't break when the screen resolution changes.
this makes it work on compositors that support on the fly
screen resize, or that swap screen width and height on screen rotation
> if the screen resolution changes, resize keyboard window

- CMakeLists.txt
- com.github.maliit.keyboard.desktop
This way it can be used for easily listing on configuration modules.
Here's some context:
* https://invent.kde.org/frameworks/kservice/-/merge_requests/35
* https://invent.kde.org/plasma/kwin/-/merge_requests/565
> Provide a desktop file for maliit

- src/plugin/feedback.cpp
10ms is bit too fast to notice.
I tested this on PinePhone device with ffmemless driver, and 10ms barely activates vibrator gpio driver before simply turning it off.
> Set haptic feedback duration to 150ms

- data/themes/Breeze.json
- data/themes/BreezeDark.json
This theme is used in Plasma Mobile currently.
If you prefer to not ship this in maliit repo, let me know and I will ship this in plasma-phone-components or something. That said there already is for example ubuntu specific colorschemes here, so this does not hurt. Thoughts welcome.
Authored-by: Devin Lin
> themes: add Breeze color schemes

- data/devices/default.json
Current sizing is bit too huge, and results in stretched keyboard keys.
which looks bit weird, and also is not usable in vertical form factor at
all.
Before:
After:
> Provide sensible default sizing

- data/themes/BreezeDark.json
The BreezeDark theme divider color was made to be too light, darken it a bit so it does not stick out.
Before:
After:
> Fix BreezeDark theme divider color

- README.md
- src/lib/coreutils.cpp
- src/lib/coreutils.h
- src/plugin/device.cpp
- src/plugin/device.h
- src/plugin/feedback.cpp
- src/plugin/feedback.h
- src/plugin/theme.cpp
- src/plugin/theme.h
This should fix #2.
As a slight derivation from the discussion held in #2, I wrote for the README.md that LGPL-3.0-or-later code is also fine in `qml` after I saw that basically everything there is LGPL'ed anyway. I hope that is OK.
I've also taken the liberty to adjust the license header of files created by @jpetersen but using a LGPL header, as he agreed there that he'd adjust his code to BSD licensing. I assume that's still OK for you, @jpetersen, and you merely forgot to modify them?
> Clarify licensing. Fix #2.

- src/lib/logic/wordengine.cpp
Hopefully trivial enough to not need more explanation.
> Don't crash when no language plugin is loaded

- data/devices/tablet.json
The key name should be `wordRibbonHeight`.
> Fix incorrect key name in tablet.json

- plugins/pinyin/qml/Keyboard_zh-hans.qml
- qml/languages/Keyboard_symbols_zh-hans.qml
In this pull request, we made two changes.
1. Make the extended area of the main keyboard display only valid pinyin symbols.
2. Optimise the symbol area for Simplified Chinese by using full-width punctuations by default, and adding half-width characters to the extended area.
Something to consider before merging: putting `Keyboard_symbols_zh-hans.qml` in the same directory as `Keyboard_symbols.qml` does not look elegant enough, as if one adds more languages like this, `qml/languages` will just contain too many files. I would rather put it under `plugins/pinyin/qml` but what would be the correct way to refer to the symbols file in `Keyboard_zh-hans.qml`?
> Optimise keyboard for Simplified Chinese

- src/lib/models/layout.h
- src/plugin/inputmethod.h
It adds more information to our metaobject and makes it easier to
introspect. Makes it possible to have it printed properly by QDebug.
> Use Q_ENUM

- COPYING
- COPYING.LGPL
As the Lesser GPL is a set of exceptions for the GPL, both need
to be included in the repository and distribution.
> Replace COPYING with full GPL and add COPYING.LGPL

- qml/keys/LanguageMenu.qml
- src/plugin/inputmethod.cpp
- src/plugin/inputmethod.h
Moves the call into a C++ class.
Checks the system being run using the XDG_CURRENT_DESKTOP.
Prevents us from forwarding the QT_WAYLAND_SHELL_INTEGRATION value to
the child process, since it will not work as expected as we are
enforcing a private one. Made the switch for all desktops as I
understand it's the same problem elsewhere.
Note, this will only work properly as of Plasma 5.23 (October). The current case is already broken so I'd say we can safely get this in and eventually have it all converge.
> Make sure Settings also work when running on Plasma

- qml/Keyboard.qml
* Some apps (like `Konsole`) seem to not correctly report whether there is content after the cursor.
* This was causing right swipes to not move the cursor to the right.
* Additionally, `processSwipe` was only called `onMouseXChanged`, while `processSwipe` currently takes action on both horizontal and vertical input.
> left/right arrow keypress: Don't check for surrounding text

- CMakeLists.txt
- data/themes/Ambiance.json
- data/themes/BorderedBlack.json
- data/themes/BorderedGrey.json
- data/themes/BorderedWhite.json
- data/themes/Breeze.json
- data/themes/BreezeDark.json
- data/themes/JustBlack.json
- data/themes/JustGrey.json
- data/themes/JustWhite.json
- data/themes/SuruBlack.json
- data/themes/SuruDark.json
- qml/keys/ActionKey.qml
- qml/keys/BackspaceKey.qml
- qml/keys/KeyIcon.qml
- qml/keys/ShiftKey.qml
- src/plugin/iconprovider.cpp
- src/plugin/iconprovider.h
- src/plugin/inputmethod_p.h
- src/plugin/theme.cpp
- src/plugin/theme.h
This needs https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/121 for the icons to work with the Breeze themes, or https://gitlab.com/ubports/core/suru-icon-theme installed (may be available in some distributions already) for the other themes.
> Bring back support for icon themes

- plugins/emoji/qml/Keyboard_emoji.qml
With icon theme support, it seems the language key on the emoji layout
is now sowing both text and icon overlapped. As 'ABC' is untranslated
and doesn't make sense to have for many languages, just remove the
label from it, and rely on the language icon instead.
> Remove label from language key on emoji keyboard

- qml/keys/SpaceKey.qml
Currently every key on the keyboard except the spacebar keys has press feedback. Add it to this key as well so it doesn't feel awkward.
> Make spacebar key vibrate/sound on press

- src/plugin/feedback.cpp
Currently vibrations are far too long and strong on all devices I've tested (OP6, Pinephone, Pinephone Pro), and get mixed up with other keypresses. 100ms is the shortest duration that the Pinephone can actually register. While a much lower duration would be optimal for other devices (Pinephone Pro, Oneplus 6), this strikes a balance for now so that every device can have vibration effects.
In the future, we really need some facility in order to define vibration profiles for each device, since motors can vary wildly.
> Set haptic feedback duration to 100ms and intensity to 0.5

- CMakeLists.txt
As newer GCC versions default to C++17 and presage headers are not
compatible, we need to specify an older standard, to compile
> Build with C++14 when presage is enabled

- po/CMakeLists.txt
We were using a command to generate the pot files and it got all
confused because the pot file is both the target and the result.
Instead we use add_custom_command() and we tell it's to generate the .pot
file as its OUTPUT.
> Fix the build using ninja

- CMakeLists.txt
- qml/WordRibbon.qml
For some reason, the maliit fork was defaulting to myspell dictionaries path, rather than hunspell, so correct that. Also removes an extraneous rectangle in the word ribbon, which prevented the active press visual feedback through state changes, and uses the correct colors from the selected theme.
> Fixes for spell checking

- qml/Keyboard.qml
- src/plugin/inputmethod.cpp
- src/plugin/inputmethod.h
- src/plugin/inputmethod_p.h
Currently, the animation for showing or hiding the keyboard is done
client side. This leads to some nasty race conditions, at least on KWin
Wayland, because the keyboard rect is sent asynchronously and any window
geometry changes it causes are also async.
To allow the animation to be done by the compositor directly, we first
need to disable the client-side animation.
> Allow disabling show/hide animations with an environment variable

- data/schemas/org.maliit.keyboard.maliit.gschema.xml
- qml/Keyboard.qml
- qml/KeyboardContainer.qml
- qml/keys/LanguageKey.qml
- src/plugin/inputmethod.cpp
- src/plugin/inputmethod.h
- src/plugin/inputmethod_p.h
- src/plugin/keyboardsettings.cpp
- src/plugin/keyboardsettings.h
This makes switching layouts much less confusing now, behaving more like the keyboards on other modern OSes, by simply cycling through all the enabled layouts.
> Improve layout switching behavior

- CMakeLists.txt
- cmake/FindAnthyUnicode.cmake
anthy is no longer maintained currently and anthy-unicode is generated
to convert internal EUC data to UTF-8 and maintained.
If anthy-unicode package is found, it can be used instead of anthy.
> Enable anthy-unicode build

- plugins/ko/src/koreanplugin.cpp
- plugins/ko/src/koreanplugin.h
- plugins/pinyin/src/pinyinadapter.cpp
- plugins/westernsupport/spellpredictworker.cpp
- plugins/westernsupport/spellpredictworker.h
- plugins/westernsupport/westernlanguagesplugin.cpp
- plugins/westernsupport/westernlanguagesplugin.h
- src/lib/logic/wordengine.cpp
- src/plugin/updatenotifier.cpp
- src/plugin/updatenotifier.h
This also affects the ABI/API to a considerable extent.
.
However, before uploading this package to Debian, I'd prefer to
see this amended.
> {plugins,src}/: Fix typo ('overridden' is spelled with double 'd').

- qml/KeyboardContainer.qml
With the change of emoji layout to being a state instead of a plugin, the
loader was always active, causing a slight reduction in performance with
showing the keyboard when requested. This change fixes that by only loading
the emoji QML when the emoji state is requested by the user.
> qml: Only load emoji keyboard QML when the state is EMOJI

- qml/ActionsToolbar.qml
- qml/Keyboard.qml
- qml/WordRibbon.qml
Instead of getting these values from a device config, try to simply use
some values which may scale better across varying display sizes.
Fixes #36
> qml: Adjust WordRibbon height and font size to scale better

- cmake/FindPinyin.cmake
This is supposed to be an optional dependency but it was always appending `Glib2` stuff to both `Pinyin_LIBRARIES` and `Pinyin_INCLUDE_DIRS` which in turn caused `find_package(Pinyin)` to set a non-falsy `Pinyin_FOUND` value and running the top-level `if(Pinyin_FOUND)` branch unconditionally:
```
Package libpinyin was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpinyin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpinyin' found
-- Found GLib2: /usr/aarch64-linux-musl/usr/lib64/libglib-2.0.so;/usr/aarch64-linux-musl/usr/lib64/libglib-2.0.so
-- Found Pinyin: Pinyin_LIBRARIES-NOTFOUND;/usr/aarch64-linux-musl/usr/lib64/libglib-2.0.so;/usr/aarch64-linux-musl/usr/lib64/libglib-2.0.so
...
-- Configuring done
CMake Error: The …
```
> Fix builds without Pinyin

- qml/Keyboard.qml
- qml/keys/ActionsToolbarButton.qml
- qml/keys/CharKey.qml
- qml/keys/FloatingActionKey.qml
Fix the following deprecation warnings from Qt 5.15:
Implicitly defined onFoo properties in Connections are deprecated.
Use this syntax instead: function onFoo(<arguments>) { ... }
Fixes #140
> qml: Use new syntax for Connections components

- qml/keys/CharKey.qml
- qml/keys/ExtendedKeysSelector.qml
There are a couple of especially long extended key lists in some of the
keyboard layouts, so split them into two rows. This currently only supports
having two rows, but could be extended to up to three rows in the future
if necessary. Generally, keys shouldn't have so many extended keys on a
single character key, though.
> qml: Implement a grid layout for longer extended keys lists

- qml/keys/Magnifier.qml
Change the Magnifier so that it looks more connected to the key it represents, by matching the width while doubling the height, and ensuring the label remains in the top half above the key.
> magnifier: Adjust dimensions to match key width

- qml/keys/CharKey.qml
Make annotation font size slightly smaller to avoid potential overlap with main label, and set display mode of the ToolButton component to IconOnly if main label is empty, or TextOnly otherwise.
> Small improvements to CharKey

- qml/WordRibbon.qml
On Steam Deck, after the previous word ribbon height adjustments, the text
remained quite small, so just use ribbon height / 2 now for font size, to
keep the relative size more consistent across devices.
> qml: Adjust word ribbon height to be less dependent on device units

- qml/keys/PressArea.qml
When the keyboard hides, pressed would remain true and hover events would still trigger as if the drag session never finished.
This makes sure that the press area gets disabled and the swipe works on consecutive Panel sessions.
> Make sure PressArea gets reset when the keyboard hides

- src/plugin/feedback.cpp
Change it to the original value prior to when it was hardcoded specifically for the PinePhone vibration motor: https://github.com/maliit/keyboard/pull/25.
Hardcoding it to long intervals makes the keyboard kind of unusable for non-pinephone devices. 
To properly fix this for the pinephone, it should be done from the vibration driver or underlying stack, not from here
> Change vibration duration to 10ms

- plugins/ru/qml/Keyboard_ru_url.qml
- plugins/ru/qml/Keyboard_ru_url_search.qml
In Russian layouts, the extended keys list contains the [.укр](https://en.wikipedia.org/wiki/.%D1%83%D0%BA%D1%80) domain without a dot. Please add a dot
> qml: Fix .укр domain on ru keypad

- plugins/fa/qml/Keyboard_fa.qml
As i had mentioned in #208 , Persian keyboard symbol wouldn't get opened at all, so i changed the symbol directory in the main qml and also i tweaked the layout making it easier to use.
> Fixed Persian Keyboard symbols
